In [1]:
import os

import math
import cv2
import numpy

from PIL import Image
import pandas as pd

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.utils import shuffle

import matplotlib.pyplot as plt

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D


Base_dir='/Users/shreevathsapk/Desktop/Dipprj'
os.chdir(Base_dir)


Using TensorFlow backend.


In [2]:
def imagepreprocess(image_folders_dir):
    Numpy_img_array=[];
    Label_array=[];
    os.chdir(image_folders_dir)
    for filename in os.listdir(image_folders_dir):
        if(filename!='.DS_Store'):
            print(filename)
            #print(Numpy_img_array)
            os.chdir(filename)
            for imgclass_file in os.listdir():
                #print("In for2 ",filename)
                if imgclass_file.endswith(('.jpg', '.png')):
                    #print('if check')
                    spctimg_highquality=cv2.imread(imgclass_file) #cv2.cvtColor(originalImage, cv2.COLOR_BGR2GRAY)
                    spctimg=cv2.resize(spctimg_highquality,(45,45))
                    #spctimg=cv2.cvtColor(spctimg_color, cv2.COLOR_BGR2GRAY)
                    Numpy_img_array.append(spctimg)
                    Label_array.append(filename);
            os.chdir("..")
            print(os.getcwd())
    os.chdir("..") 
    return Numpy_img_array,Label_array

In [3]:

def Conv_Neural_Net(x_train,y_train,x_test,y_test):
    #x_train=Image_Data
    #y_train=Label_Data
    
    #create model
    model = Sequential()
    #add model layers
    model.add(Conv2D(64, kernel_size=1, activation='relu',input_shape=(45,45,3)))
    model.add(Conv2D(32, kernel_size=1, activation='relu'))
    model.add(Flatten())
    model.add(Dense(11, activation='softmax'))
    
    #compile model using accuracy to measure model performance
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    
    #train the model
    model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=3)
    return model

In [4]:
 def Dataset_organise(Image_Data_list,Label_Data):
    Image_Data=numpy.stack(Image_Data_list, axis=0 )
    #Image_Data_list=0; ###Clearing the variable to save space in disk

    encoder = LabelEncoder()
    Label_Data_enc = encoder.fit_transform(Label_Data)


    randomize = numpy.arange(len(Image_Data))
    numpy.random.shuffle(randomize)
    Image_Data = Image_Data[randomize]
    Label_Data_enc = Label_Data_enc[randomize]

    Image_Data_Train=Image_Data[:math.ceil(len(Image_Data)*0.8)]
    Image_Data_Test=Image_Data[math.ceil(len(Image_Data)*0.8):len(Image_Data)]


    Label_Data_Train=Label_Data_enc[:math.ceil(len(Label_Data_enc)*0.8)]
    Label_Data_Test=Label_Data_enc[math.ceil(len(Label_Data_enc)*0.8):len(Label_Data_enc)]

    #Image_Data=0; ###Clearing the variable to save space in disk
    
    return Image_Data_Train,Image_Data_Test,Label_Data_Train,Label_Data_Test

In [5]:
#main
os.chdir(Base_dir)
image_folders_dir='/Users/shreevathsapk/Desktop/Dipprj/imagesamp'

[Image_Data_list,Label_Data]=imagepreprocess(image_folders_dir)

9
/Users/shreevathsapk/Desktop/DIPPrj/imagesamp
0
/Users/shreevathsapk/Desktop/DIPPrj/imagesamp
7
/Users/shreevathsapk/Desktop/DIPPrj/imagesamp
6
/Users/shreevathsapk/Desktop/DIPPrj/imagesamp
1
/Users/shreevathsapk/Desktop/DIPPrj/imagesamp
10
/Users/shreevathsapk/Desktop/DIPPrj/imagesamp
8
/Users/shreevathsapk/Desktop/DIPPrj/imagesamp
4
/Users/shreevathsapk/Desktop/DIPPrj/imagesamp
3
/Users/shreevathsapk/Desktop/DIPPrj/imagesamp
2
/Users/shreevathsapk/Desktop/DIPPrj/imagesamp
5
/Users/shreevathsapk/Desktop/DIPPrj/imagesamp


In [6]:
[Image_Data_Train,Image_Data_Test,Label_Data_Train,Label_Data_Test]=Dataset_organise(Image_Data_list,Label_Data)

In [7]:
instrumentclassificationmodel=Conv_Neural_Net(Image_Data_Train,Label_Data_Train,Image_Data_Test,Label_Data_Test)

Train on 2200 samples, validate on 550 samples
Epoch 1/3
2200/2200 [==============================] - 6s 3ms/step - loss: 12.8974 - accuracy: 0.5359 - val_loss: 0.3599 - val_accuracy: 0.8764
Epoch 2/3
2200/2200 [==============================] - 5s 2ms/step - loss: 0.1952 - accuracy: 0.9368 - val_loss: 0.0857 - val_accuracy: 0.9691
Epoch 3/3
2200/2200 [==============================] - 5s 2ms/step - loss: 0.0629 - accuracy: 0.9827 - val_loss: 0.0614 - val_accuracy: 0.9800


In [8]:
predictions = instrumentclassificationmodel.predict_classes(Image_Data_Test)
predictions

array([ 7,  7,  6,  5,  9,  2,  3,  4,  8,  8, 10,  0,  5,  6, 10,  0,  4,
        8, 10, 10,  7,  9,  5,  0,  4,  7,  3,  6, 10,  3,  8,  4,  2,  3,
        1,  2,  6,  7,  0,  5,  3,  1,  6,  9,  4,  3,  2,  5,  8,  4,  9,
        4,  8,  2, 10,  5,  5,  5,  3,  9,  0,  9,  9, 10,  7,  8,  4,  3,
        8,  2,  6,  6,  8,  7,  1,  5,  2,  4,  6,  4,  1,  1,  3,  0,  6,
        8,  9,  1, 10,  5,  3,  5, 10,  2,  0,  1,  7,  0,  0,  3,  8,  4,
        1,  6,  9,  6,  4,  6,  5,  4,  9,  7,  9,  7,  0,  5, 10,  9,  7,
        1,  9,  5,  2,  7,  5,  4,  0,  4,  0, 10,  4,  3,  8,  5,  1,  5,
        9,  4,  4,  6,  2,  5,  3,  7,  3,  4,  7,  6,  7,  1,  7,  1,  3,
        5,  8,  3, 10,  2,  6,  7,  5,  0,  3,  2,  4,  4,  0,  5,  1, 10,
        1,  5,  4, 10,  0,  1,  1, 10, 10,  4,  4,  8,  2,  6,  2,  8,  2,
        3,  4,  4,  4,  9,  9, 10,  5, 10,  4,  2,  9,  3,  8,  6,  7,  9,
        9,  7,  4,  3,  5,  0,  8,  5,  9,  4,  1,  1,  1,  3,  9,  6,  4,
       10,  9,  7,  3, 10

In [9]:
C=confusion_matrix(Label_Data_Test, predictions)

In [10]:
C

array([[44,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0, 51,  0,  0,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 40,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  2, 48,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 55,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 56,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 45,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 52,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 51,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 45,  0],
       [ 0,  0,  1,  1,  0,  0,  0,  0,  0,  0, 52]])

In [11]:
K=(C / C.astype(numpy.float).sum(axis=1))*100
K

array([[ 88.        ,   0.        ,   0.        ,   0.        ,
         10.90909091,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [  0.        ,  98.07692308,   0.        ,   0.        ,
          1.81818182,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        , 100.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   5.        ,  96.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
        100.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        , 100.        ,   0. 

In [12]:
for i in range (6):
    print(K[i][i])

88.0
98.07692307692307
100.0
96.0
100.0
100.0


In [13]:
'''
def prediction_spectrum_extract(audio_file):
    cmap = plt.get_cmap('inferno')
    y, sr = librosa.load(audio_file, mono=True,duration=20)
    plt.specgram(y, NFFT=2048, Fs=2, Fc=0, noverlap=128, cmap=cmap, sides='default', mode='default', scale='dB');
    plt.axis('off');
    plt.savefig(f'/Users/shreevathsapk/Desktop/Miniprj/CNN_Prediction_features/{audio_file[:-3].replace(".", "")}.png')
    '''

'\ndef prediction_spectrum_extract(audio_file):\n    cmap = plt.get_cmap(\'inferno\')\n    y, sr = librosa.load(audio_file, mono=True,duration=20)\n    plt.specgram(y, NFFT=2048, Fs=2, Fc=0, noverlap=128, cmap=cmap, sides=\'default\', mode=\'default\', scale=\'dB\');\n    plt.axis(\'off\');\n    plt.savefig(f\'/Users/shreevathsapk/Desktop/Miniprj/CNN_Prediction_features/{audio_file[:-3].replace(".", "")}.png\')\n    '

In [14]:

def prediction_features(imagefile_path):
    old_dir=os.getcwd()
    os.chdir(imagefile_path)
    image_file=input()
    spctimg_highquality=cv2.imread(image_file) #cv2.cvtColor(originalImage, cv2.COLOR_BGR2GRAY)
    spctimg=cv2.resize(spctimg_highquality,(45,45))
    processed_image_prediction=numpy.stack(spctimg, axis=0 )
    os.chdir(old_dir)
    return processed_image_prediction

In [19]:
image_file_prediction_path=input('Give Pediction file path')

Give Pediction file path /Users/shreevathsapk/Desktop


In [33]:
processed_image_prediction=prediction_features(image_file_prediction_path)

 el.jpg


In [34]:
processed_image_prediction1 = numpy.asarray(processed_image_prediction).reshape((1, 45, 45, 3))
recognised_emoji = instrumentclassificationmodel.predict_classes(processed_image_prediction1)

In [35]:
processed_image_prediction.shape

(45, 45, 3)

In [36]:
recognised_emoji[0]

1

In [24]:
predictions

array([ 7,  7,  6,  5,  9,  2,  3,  4,  8,  8, 10,  0,  5,  6, 10,  0,  4,
        8, 10, 10,  7,  9,  5,  0,  4,  7,  3,  6, 10,  3,  8,  4,  2,  3,
        1,  2,  6,  7,  0,  5,  3,  1,  6,  9,  4,  3,  2,  5,  8,  4,  9,
        4,  8,  2, 10,  5,  5,  5,  3,  9,  0,  9,  9, 10,  7,  8,  4,  3,
        8,  2,  6,  6,  8,  7,  1,  5,  2,  4,  6,  4,  1,  1,  3,  0,  6,
        8,  9,  1, 10,  5,  3,  5, 10,  2,  0,  1,  7,  0,  0,  3,  8,  4,
        1,  6,  9,  6,  4,  6,  5,  4,  9,  7,  9,  7,  0,  5, 10,  9,  7,
        1,  9,  5,  2,  7,  5,  4,  0,  4,  0, 10,  4,  3,  8,  5,  1,  5,
        9,  4,  4,  6,  2,  5,  3,  7,  3,  4,  7,  6,  7,  1,  7,  1,  3,
        5,  8,  3, 10,  2,  6,  7,  5,  0,  3,  2,  4,  4,  0,  5,  1, 10,
        1,  5,  4, 10,  0,  1,  1, 10, 10,  4,  4,  8,  2,  6,  2,  8,  2,
        3,  4,  4,  4,  9,  9, 10,  5, 10,  4,  2,  9,  3,  8,  6,  7,  9,
        9,  7,  4,  3,  5,  0,  8,  5,  9,  4,  1,  1,  1,  3,  9,  6,  4,
       10,  9,  7,  3, 10

In [ ]:
Label_Data_Test-predictions